export const browserCoreExamples = [
  "ClosedClaw browser status",
  "ClosedClaw browser start",
  "ClosedClaw browser stop",
  "ClosedClaw browser tabs",
  "ClosedClaw browser open https://example.com",
  "ClosedClaw browser focus abcd1234",
  "ClosedClaw browser close abcd1234",
  "ClosedClaw browser screenshot",
  "ClosedClaw browser screenshot --full-page",
  "ClosedClaw browser screenshot --ref 12",
  "ClosedClaw browser snapshot",
  "ClosedClaw browser snapshot --format aria --limit 200",
  "ClosedClaw browser snapshot --efficient",
  "ClosedClaw browser snapshot --labels",
];

export const browserActionExamples = [
  "ClosedClaw browser navigate https://example.com",
  "ClosedClaw browser resize 1280 720",
  "ClosedClaw browser click 12 --double",
  'ClosedClaw browser type 23 "hello" --submit',
  "ClosedClaw browser press Enter",
  "ClosedClaw browser hover 44",
  "ClosedClaw browser drag 10 11",
  "ClosedClaw browser select 9 OptionA OptionB",
  "ClosedClaw browser upload /tmp/file.pdf",
  'ClosedClaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "ClosedClaw browser dialog --accept",
  'ClosedClaw browser wait --text "Done"',
  "ClosedClaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "ClosedClaw browser console --level error",
  "ClosedClaw browser pdf",
];
